import '../../node_modules/modern-normalize/modern-normalize.css';
import '../scss/style.scss';

import { initModals } from './components/Modal';
import { initPathToSuccess } from './components/PathToSuccess';
import { initHero } from './components/Hero';
import { initBurgerMenu } from './components/BurgerMenu';
import { showServicesInfo } from './components/concept';
import { initStartInNumbers } from './components/StartInNumbers';
import { initAccordion } from './components/Accordion';
import { header } from './components/header';
import { initCountdownTimer } from './components/Countdown';
import { initSwipers } from './services/Swiper';
import { initTabs } from './utils/Tabs';
import { initCatalog } from './components/ServicesCatalog';
import { initYaMap } from './services/YaMap';
import { scrollAnimation } from './services/scroll-animation';
import { initForms } from './services/Form';
import { initControls } from './components/FormControl';
import { initPhoneMasks } from './services/PhoneMask';

document.addEventListener('DOMContentLoaded', () => {
  initControls();
  initHero();
  initStartInNumbers();
  initPathToSuccess();
  showServicesInfo();
  initBurgerMenu();
  initModals();
  initAccordion();
  initSwipers();
  initTabs();
  initCatalog();
  header();
  initCountdownTimer();
  initYaMap();
  scrollAnimation();
  initForms();
  initPhoneMasks();
});
